@AiShortsGenerator_LocalAddress = http://localhost:5211
@AiShortsGenerator_DockerAddress = http://localhost:8080

### Test the Gemini API
POST {{AiShortsGenerator_LocalAddress}}/generate-content
Content-Type: application/json

{
  "input": "Tell me a story about a brave knight."
}

### Test the Text-to-Speech API
POST {{AiShortsGenerator_LocalAddress}}/generate-audio
Content-Type: application/json

{
  "input": "Hello, this is a test."
}

### Donwload Audio File
GET {{AiShortsGenerator_LocalAddress}}/download-audio/1
