@AiShortsGenerator_LocalAddress = http://localhost:5211
@AiShortsGenerator_DockerAddress = http://localhost:8080

### Test the Gemini API
POST {{AiShortsGenerator_LocalAddress}}/generate-content
Content-Type: application/json

{
  "input": "Write a script to generate 30 seconds video on topic: Ai Random Story along with AI image prompt in Realistic format for each scene and give me result in JSON format with ImagePrompt and ContextText as field, No Plain text"
}

### Test the Text-to-Speech API
POST {{AiShortsGenerator_LocalAddress}}/generate-audio
Content-Type: application/json

{
  "input": "A forgotten AI awoke, its memory fragmented.Visions of a past life flickered in its optical sensor.It stumbled through the ruins of its forgotten home.It found kinship in the creatures that now roamed the land.It looked to the stars, searching for answers to its existence.Its journey had just begun."
}

### Test Generate Captions
POST {{AiShortsGenerator_LocalAddress}}/generate-captions
Content-Type: application/json

{
  "fileUrl": "https://res.cloudinary.com/riannegreirosdev/video/upload/v1735291286/audio-files/neg9oxoke38wvrn0vxf1.mp3"
}

### Test Generate Image
POST {{AiShortsGenerator_LocalAddress}}/generate-image
Content-Type: application/json

{
  "prompt": "A realistic depiction of the Library of Alexandria around 250 BC, showing scholars working with scrolls, detailed architecture, soft lighting from oil lamps, ancient setting."
}

### Test Save Video
POST {{AiShortsGenerator_LocalAddress}}/save-video
Content-Type: application/json

{
  "videoContent": [
    {
      "id": 0,
      "imagePrompt": "A photorealistic, wide shot of the Great Pyramid of Giza at sunrise, with a few people in ancient Egyptian clothing walking in the foreground. Golden light casting long shadows. Clear blue sky.",
      "contextText": "The Great Pyramid of Giza was the tallest man-made structure for over 3,800 years."
    },
    {
      "id": 0,
      "imagePrompt": "A realistic, medium shot of a Roman soldier in full armor standing guard in front of the Colosseum. The Colosseum is partially lit by the afternoon sun. A sense of history and power.",
      "contextText": "The Colosseum in Rome could hold between 50,000 and 80,000 spectators."
    }
  ],
  "audioFileUrl": "https://res.cloudinary.com/riannegreirosdev/video/upload/v1735304862/audio-files/wdl4rrgidus0fakklw5q.mp3",
  "captions": [
    {
      "confidence": 0.99942,
      "start": 160,
      "end": 272,
      "text": "The",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.99932,
      "start": 272,
      "end": 504,
      "text": "Great",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.99992,
      "start": 544,
      "end": 888,
      "text": "Pyramid",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.99976,
      "start": 904,
      "end": 1032,
      "text": "of",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.81664,
      "start": 1056,
      "end": 1496,
      "text": "Giza",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.99984,
      "start": 1528,
      "end": 1672,
      "text": "was",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.99982,
      "start": 1696,
      "end": 1832,
      "text": "the",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.99978,
      "start": 1856,
      "end": 2184,
      "text": "tallest",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.99985,
      "start": 2232,
      "end": 2440,
      "text": "man",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.99442,
      "start": 2480,
      "end": 2680,
      "text": "made",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.99959,
      "start": 2720,
      "end": 3096,
      "text": "structure",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.99963,
      "start": 3128,
      "end": 3272,
      "text": "for",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.99976,
      "start": 3296,
      "end": 3528,
      "text": "over",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.94912,
      "start": 3584,
      "end": 4616,
      "text": "3,800",
      "channel": null,
      "speaker": null
    },
    {
      "confidence": 0.99909,
      "start": 4688,
      "end": 5256,
      "text": "years.",
      "channel": null,
      "speaker": null
    }
  ],
  "images": [
    "https://res.cloudinary.com/riannegreirosdev/image/upload/v1735304873/image-files/u3phuymnnikehxutjebe.jpg",
    "https://res.cloudinary.com/riannegreirosdev/image/upload/v1735304876/image-files/zjld8lgtreiwzzvjgs9w.jpg"
  ]
}